
	
	

	  
	#ifndef __GUI_H
	#define __GUI_H
	
	
	#include "mouse.h"
         static Navigate navigate;	
	
	#include "global.h"	
    #include "button.h"
    #include "window.h"
    #include "menu.h"
	
	//#include "textbox.h"
	
	//#include "label.h"
	
	//#include "msgbox.h"
	
	//MsgBox msgbox;
		
	#include "mouse.cpp"	
	#include "button.cpp"
	//#include "textbox.cpp"
	#include "window.cpp"
	//#include "label.cpp"
	#include "menu.cpp"
    
	//#include "msgbox.cpp"
	
	
	
		

	#endif // __GUI_H


 	
      
    			


















	

 
